# by me controllers:
# by me   resource: ../../src/Controller/
# by me   type: annotation

web_pub:
    resource: ../../src/Presentation/Web/Frontend/Controller/
    type: annotation
web_backoffice:
    resource: ../../src/Presentation/Web/Backend/Controller/
    type: annotation
    prefix: /admin
api_rest:
    resource: ../../src/Presentation/Api/Rest/Controller/
    type: annotation
    prefix: /api